<DezeApp>:

	canvas:
		Rectangle:
			size:self.width,self.height
			source: "Stones in wood.jpg"
		Color:
			rgba:1,1,1,1
		Ellipse:
			size:300,300
			pos:25,150

	BoxLayout:
		orientation: "horizontal"
		Label:
			text:"1"
			color: 1,1,0,1
			background_color: 1,1,0,1

		Label:
			canvas.before:
				Color:
					rgba:1,0,0,.5
				Ellipse:
					pos:self.pos
					size: self.size
					source:"druide.png"


			text:"2"
			size_hint: 1,1
		Label:
			text:"3"

	BoxLayout:
		orientation:"vertical"

		Label:
			canvas.before:
				Color:
					rgba:1,0,0,.5
				Rectangle:
					pos:self.pos
					size: self.size
			text:"A"
			size_hint: 1,1

		Label:
			id: _kern_label
			canvas.before:
				Color:
					rgba:1,0,0,.5
				Ellipse:
					pos:self.pos
					size: self.size
			text:"b"
			size_hint:1,1
			pos_hint:{"center_x":.5,"center_y":.5}
		Label:
			canvas.before:
				Color:
					rgba:1,0,0,.5
				Rectangle:
					pos:self.pos
					size: self.size
			text:"C"
			size_hint: 1,1
	BoxLayout:
		Label:
			text:"Een"
		Label:
			text:"Twee"
		Label:
			text:"Drie"

	#BoxLayout:
		#orientation:"vertical"
		#Button:
		#	text: "press"
		#	on_press: _kern_label.text="Mooi\n werk\n Ardan"